### ISSUE TITLE
cron mail clutter when no batteries connected

### ISSUE THREAD

**Issue by nachtgeist** [petterreinholdtsen/battery-status#18]
/usr/share/battery-stats/collect-csv prints errors when no batteries are connected, resulting in cron mail clutter like

-----8<------
Subject: Cron root@localhost    if [ -x /usr/share/battery-stats/collect-csv ]; then /usr/share/battery-stats/collect-csv ; fi (failed)

/usr/share/battery-stats/collect-csv: line 86: cd: BAT*: No such file or directory
-----8<------

**Comment by petterreinholdtsen** [comment]
Please use the battery-stats repo instead.  It is taking over for this repo.

**Comment by nachtgeist** [comment]
will do, thanks
