### ISSUE TITLE
suspend/resume hooks don't run in jessie

### ISSUE THREAD

**Issue by anarcat** [petterreinholdtsen/battery-status#8]
for some reason, suspend/resume hooks don't run here and the data doesn't get collected then.

**Comment by petterreinholdtsen** [comment]
Hm, perhaps systemd do not work with /etc/pm/?  I must admit I just recently upgraded from Wheezy, and have not checked if the /etc/pm/ scripts still work with Jessie.

**Comment by anarcat** [comment]
i am not sure i am ready to blame systemd just yet. :) i have /etc/pm stuff installed here:

```
$ dpkg -S /etc/pm
unattended-upgrades, toshset, pm-utils: /etc/pm
```

i am not sure they get fired when my laptop gets suspended/resumed, but then again, i am not sure how that happens in the first place. it _may_ be systemd doing the suspend, but it could also be the laptop's BIOS as well: it's unclear. i know that suspend happens when i close the lid, but that's about it.

**Comment by petterreinholdtsen** [comment]
[anarcat]

> i am not sure i am ready to blame systemd just yet. :)

I did not really try to blame systemd, just know that systemd is trying
to handle suspend/resume and that this has caused problems in the
migration, when at least KDE wanted to handle it too.  I've seen bug
reports about a machine going into suspend as it should, getting back up
on resume, and imediately going into suspend again.  The cause was both
systemd and some KDE related power management software trying to do the
suspend, and one would win and do it first, and the other would loose
and do it shortly after the first resume.  I believe this issue has been
fixed now by leaving the suspend handling to systemd.  If that is the
case, I guess systemd is responsible for calling scripts in /etc/pm/
too.

I do not really know how these things work, and am only guessing. :)

## 

Happy hacking
Petter Reinholdtsen

**Comment by anarcat** [comment]
On 2015-09-25 17:35:52, petterreinholdtsen wrote:

> I do not really know how these things work, and am only guessing. :)

Same here. :) I would assume that systemd should call those scripts,
maybe it's a bug that we should look for... too tired for this right now
:)

## cheers!

Wire telegraph is a kind of a very, very long cat. You pull his tail
in New York and his head is meowing in Los Angeles. Radio operates
exactly the same way: you send signals here, they receive them
there. The only difference is that there is no cat.
                         - Albert Einstein

**Comment by petterreinholdtsen** [comment]
[anarcat]

> Same here. :) I would assume that systemd should call those scripts,
> maybe it's a bug that we should look for... too tired for this right
> now :)

http://askubuntu.com/questions/609695/does-systemd-read-etc-pm explain
that /etc/pm/ is ignored by systemd, and suggest to provide units in
/lib/systemd/system-sleep/ instead.

## 

Happy hacking
Petter Reinholdtsen

**Comment by anarcat** [comment]
that totally looks like a bug - it would be fairly trivial to add a hook in /lib/systemd/whatever to run-parts the scripts in /etc/pm, if only for backwards compatibility...

i guess it remains to be decided here whether we want to rely on that being fixed or shipping our own scripts in systemd shims...

**Comment by petterreinholdtsen** [comment]
[anarcat]

> i guess it remains to be decided here whether we want to rely on that
> being fixed or shipping our own scripts in systemd shims...

I see no reason to wait for systemd to start running /etc/pm/ scripts,
as it might never make it into Jessie, and I want to have my package
working in Jessie today.  The easiest way is probably to add units/hooks
into systemd to call the collect script.  It do not really hurt to
collect more data, which would be the effect if both /etc/pm/ scripts
and units run at the same time.

## 

Happy hacking
Petter Reinholdtsen

**Comment by anarcat** [comment]
agreed, as it is only discreet events like suspend/resume, which do not occur as often.

if it meant doubling the recurring sampling rate (e.g. through cron), that would be a problem, however, as the dataset would grow pretty huge.

**Comment by petterreinholdtsen** [comment]
I've commited a draft patch to enable log before and after susped/hibernate.  Please test it and let me know if it do not work.  I was unable to find a way to log when the power plug is inserted/removed.

**Comment by anarcat** [comment]
i _think_ it works, but i am not sure. it seems to log an entry on resume, not sure about suspend.

also, i had to run `systemctl daemon-reload`, i think, to make it effective... it seems to me this should be automatic in the debian package.

**Comment by petterreinholdtsen** [comment]
I'm merging this project into the battery-stats project, so please create a new issue in that project to follow up on this idea.

I would very much like to get the hooks working in newer versions of Debian.

**Comment by anarcat** [comment]
it looks like issues are disabled in https://github.com/petterreinholdtsen/battery-stats so i can't recreate the issues there...

**Comment by petterreinholdtsen** [comment]
[anarcat]

> it looks like issues are disabled in
> https://github.com/petterreinholdtsen/battery-stats so i can't
> recreate the issues there...

Oh.  I hadn't noticed.  Fixed now.

## 

Happy hacking
Petter Reinholdtsen

**Comment by anarcat** [comment]
okay, moved.
