### ISSUE TITLE
Support multiple batteries in battery-status-graph

### ISSUE THREAD

**Issue by solarnz** [petterreinholdtsen/battery-status#9]
battery-status-collect will collect statistics for all batteries that are present on the system, however battery-status-graph assumes that there is only one battery in the log file.

It would be great if battery-status-graph was able to generate separate graphs for each different battery.

**Comment by petterreinholdtsen** [comment]
[Chris Trotman]

> battery-status-collect will collect statistics for all batteries that
> are present on the system, however battery-status-graph assumes that
> there is only one battery in the log file.
> 
> It would be great if battery-status-graph was able to generate
> separate graphs for each different battery.

I agree, and patches accepted.  But until I get a laptop with multiple
batteries, I do not plan to implement it myself.:)

## 

Happy hacking
Petter Reinholdtsen

**Comment by anarcat** [comment]
if you are curious, this may be possible / easier with the numpy/matplotlib stuff in the new python grapher i worked on in #10.

i am tearing my hair out on that stuff right now, so i'd gladly let someone else deal with it as well. :)

**Comment by solarnz** [comment]
Yeah, I think that would be much easier for me to deal with in battery-status-graph.py

**Comment by anarcat** [comment]
and i forgot to mention: there are ways to produce multiple figures at once - it seems to me that seperate batteries should have separate plots, something like this:

[![multiple plots at once](http://matplotlib.org/_images/errorbar_demo_features.png)](http://matplotlib.org/examples/statistics/errorbar_demo_features.html)

withou the error bars of course...

**Comment by petterreinholdtsen** [comment]
I'm merging this project into the battery-stats project, so please create a new issue in that project to follow up on this idea.

I would love to handle more batteries in battery-stats.

**Comment by anarcat** [comment]
it looks like issues are disabled in https://github.com/petterreinholdtsen/battery-stats so i can't recreate the issues there...

**Comment by anarcat** [comment]
copied as well, this issue should be closed (but i can't do it myself).
